FROM node:13-alpine

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

USER node

RUN npm install && npm cache clean --force --loglevel=error

COPY --chown=node:node src ./src/
COPY --chown=node:node .env ./

EXPOSE 8081

CMD [ "node", "src/app.js"]